channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=22.1.2
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - lightgbm==3.3.2
  - psutil==5.9.2
  - scikit-learn==1.1.2
  - typing-extensions==4.3.0
name: mlflow-env
