datasets:
  loan:
    column_mapping:
      categorical_features:
        - 'home_ownership'
      numerical_features:
        - 'emp_length'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/Lending_Club_reduced.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
